# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Readstor < Formula
  desc "A CLI for Apple Books annotations"
  homepage "https://github.com/tnahs/readstor"
  url "https://github.com/tnahs/readstor/archive/v0.5.1.tar.gz"
  sha256 "727409b7d6fc2ad0780ab6685890fb19825d332d0e2a92fc82d01d0188bb77f0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/tnahs/readstor/releases/download/v0.5.1/readstor-0.5.1-darwin-amd64.tar.gz"
      sha256 "5dbec008dde4776b2dc352e1ee5096314d3a5ef2092c9bcb904d673c14794e7a"
    end

    on_arm do
      url "https://github.com/tnahs/readstor/releases/download/v0.5.1/readstor-0.5.1-darwin-arm64.tar.gz"
      sha256 "d949ebd78489ac77d99db4d2da98680d8f1df0ab6df4295ece8133db41a6dbbc"
    end
  end

  def install
    bin.install "readstor"
  end
end
